site_name: XDforensics-Wiki
extra:
  search:
    language: 'jp'
nav:
    - Welcome :
        - About : index.md
        - Laws and Regulations : law.md
        - Preparation : preparation.md
    - Classification : 
        - Windows: win.md
        - Linux : 
            - Linux系统基础 : Linux1.md
            - Linux应用程序 : linux2.md
            - Linux服务器 : linux3.md
            - 取证大师分析Linux镜像的方法 : linux4.md
            - 题目示例 : linux5.md
        - MacOS : mac.md
        - Mobile Devices : mobile.md
        - Packet Analysis : pac.md
        - Others : others.md
    - Write Up :
        - 2025美亚杯团体赛: MeiyaCup2025Group.md
        - 2025美亚杯个人赛: MeiyaCup2025Individual.md
        - 2025龙信杯(手机&电脑部分): Longxin2025.md
        - 2025数证杯初赛: Shuzheng2025Preliminary.md
        - 2025高校运维赛: Edu2025.md
        - 2025平航杯: Pinghang2025.md
        - 2025獬豸杯 : XieZhi2025.md
        - 2025盘古石杯决赛 : PGS2025Final.md
        - 2025盘古石杯初赛 : PGS2025Preliminary.md
        - 2025FIC决赛 : FIC2025Final.md
        - 2025FIC初赛 : FIC2025Preliminary.md
        - 2024美亚杯个人赛 : MeiyaCup2024Individual.md
        - 2024美亚杯团体赛 : MeiyaCup2024Group.md
        - 2024盘古石杯初赛 : PGS2024Preliminary.md
        - 2024盘古石杯决赛 : PGS2024Final.md
        - 2024中科实数杯 : ZKSS2024.md
        - 2024龙信杯 : Longxin2024.md
        - 2023美亚杯个人赛 : MeiyaCup2023Individual.md
        - 2023美亚杯团体赛 : MeiyaCup2023Group.md
        - 2023盘古石杯初赛 : PGS2023Preliminary.md
        - 2023中科实数杯 : ZKSS2023.md 
        - 2022长安杯 : ChanganCup2022.md
        - 2022美亚杯个人赛 : MeiyaCup2022Individual.md
        - 2022美亚杯团体赛 : MeiyaCup2022Group.md
        - 2021长安杯 : ChanganCup2021.md
        - 2021美亚杯个人赛 : MeiyaCup2021Individual.md
        - 2021美亚杯团体赛 : MeiyaCup2021Group.md
        - 2021中科实数杯 : ZKSS2021.md
        - 2020长安杯 : ChanganCup2020.md
        - 2020美亚杯团体赛 : MeiyaCup2020Group.md
        - 2019长安杯 : ChanganCup2019.md

theme:
  name: 'material'
  feature:
    tabs: true
  language: 'zh'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
